---
title: "ContinuousVariables"
output: pdf_document
---

```{r Imports}
library(tidyverse)
library(ggplot2)
```
```{r Data}

setwd('C:/Users/Administrator/Documents/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/employment')

employDisability <- read.table(file = "employDisability.csv", sep = ",", header=TRUE)
employEDUCATION <- read.csv(file = "employEDUCATION.csv")
employmentByAge <- read.table(file = "employmentByAge.csv", sep = ",", header=TRUE)
employmentByRACE <- read.table(file = "employmentByRACE.csv", sep = ",", header=TRUE)
employPoverty <- read.table(file = "employPoverty.csv", sep = ",", header=TRUE)
JobType <- read.table(file = "JobType.csv", sep = ",", header=TRUE)
```

```{r Preview Data}
employDisability 
employEDUCATION 
employmentByAge 
employmentByRACE 
employPoverty
JobType 
```
```{r Employment By Disability Plots}
employDisability

#Total number unemployed over time with disability
ggplot(data = employDisability,aes(year,Total)) + geom_line(size = 1, col = 'black') + xlab('Year') + ylab('Number Unemployed') + scale_x_continuous(breaks = seq(2010,2019)) + geom_point(size = 2.5, col = 'royalblue3')

#Unemployment Rate over time for those with disability
ggplot(data = employDisability,aes(x = year,y = UnemploymentRate)) + geom_line(size = 1, col = 'black') + xlab('Year') + ylab('Unemployment (Percent)') + scale_x_continuous(breaks = seq(2010,2019)) + scale_y_continuous(breaks = seq(20,0)) + geom_point(size = 2.5, col = 'royalblue3')
```

```{r Employment by Education Plots}
#Problem with Data Read
employEDUCATION

employEDUCATION$Label = as.factor(employEDUCATION$Label)
ggplot(data = employEDUCATION) + geom_line(aes(x = year, y = UnemploymentRate, group = Label, colour = Label),size = 1) + xlab('Year') + ylab('Unemployment (Percent)') + scale_x_continuous(breaks = seq(2010,2019)) + scale_y_continuous(breaks = seq(20,0)) 
```

```{r EmploymentByAge Plots}
#Data error, 25-44 has 2 for 2018, one should be 2019.

employmentByAge

employmentByAge$Label = as.factor(employmentByAge$Label)
ggplot(data = employmentByAge) + geom_line(aes(x = year, y = UnemploymentRate, group = Label, colour = Label),size = 1) + xlab('Year') + ylab('Unemployment (Percent)') + scale_x_continuous(breaks = seq(2010,2019)) 
```

```{r employmentByRACE Plots}
employmentByRACE

employmentByRACE$Label = as.factor(employmentByRACE$Label)
ggplot(data = employmentByRACE) + geom_line(aes(x = year,y = UnemploymentRate, group = Label, colour = Label), size = 1) + xlab('Year') + ylab('Unemployment (Percent)') + scale_x_continuous(breaks = seq(2010,2019)) 
```

```{r employPoverty Plots}
employPoverty

#Total number unemployed over time of those below Poverty line
ggplot(data = employPoverty,aes(year,Total)) + geom_line(size = 1, col = 'black') + xlab('Year') + ylab('Number Unemployed') + scale_x_continuous(breaks = seq(2010,2019)) + geom_point(size = 2.5, col = 'royalblue3')

#Unemployment Rate over time for those below Poverty line
ggplot(data = employPoverty,aes(x = year,y = UnemploymentRate)) + geom_line(size = 1, col = 'black') + xlab('Year') + ylab('Unemployment (Percent)') + scale_x_continuous(breaks = seq(2010,2019)) + geom_point(size = 2.5, col = 'royalblue3')
```

```{r JobType Plots, fig.width=14}
#Interested in getting unemployment rates for this 
JobType

JobType$Label = as.factor(JobType$Label)
ggplot(data = JobType) + geom_line(aes(x = year,y = Total, group = Label, colour = Label), size = 1) + xlab('Year') + ylab('Number unemployed') + ylim(0,1250000) + scale_x_continuous(breaks = seq(2010,2019))

```




