---
title: "EmploymentSector"
output: html_document
---
```{r Imports}
library(tidyverse)
library(ggplot2)
library(RCurl)
```
```{r Data}

employDisability <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/employDisability.csv"))
employEDUCATION <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/employEDUCATION.csv"))
employmentByAge <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/employmentByAge.csv"))
employmentByRACE <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/employmentByRACE.csv"))
employPoverty <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/employPoverty.csv"))
JobType <- read.csv(text = getURL("https://raw.githubusercontent.com/tracy3057/STAT5702_NYC_Employment_Analysis/main/DataPreprocessing/Data/employment/JobType.csv"))
```
```{r Preview Data}
employDisability 
employEDUCATION 
employmentByAge 
employmentByRACE 
employPoverty
JobType 
```

```{r Sector Plots}

JobType2010 <- JobType[JobType$year == 2010,]
JobType2011 <- JobType[JobType$year == 2011,]
JobType2012 <- JobType[JobType$year == 2012,]
JobType2013 <- JobType[JobType$year == 2013,]
JobType2014 <- JobType[JobType$year == 2014,]
JobType2015 <- JobType[JobType$year == 2015,]
JobType2016 <- JobType[JobType$year == 2016,]
JobType2017 <- JobType[JobType$year == 2017,]
JobType2018 <- JobType[JobType$year == 2018,]
JobType2019 <- JobType[JobType$year == 2019,]

ggplot(data = JobType2010[2:nrow(JobType2010),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2011[2:nrow(JobType2011),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2012[2:nrow(JobType2012),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2013[2:nrow(JobType2013),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2014[2:nrow(JobType2014),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2015[2:nrow(JobType2015),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2016[2:nrow(JobType2016),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2017[2:nrow(JobType2017),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2018[2:nrow(JobType2018),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
ggplot(data = JobType2019[2:nrow(JobType2019),], aes(x=Label,y=Total)) + geom_bar(stat = 'identity') + scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

```





