```{r}
library(tidyverse)

Education <- read.csv('/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/education/Education.csv')
Salary_edu <- read.csv('/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/education/salary_edu.csv')
NumEmp_edu <- read.csv('/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/numemp_sum_final.csv')

Education$X <- NULL
NumEmp_edu$X <- NULL
Salary_edu$X <- NULL
```

```{r}
# Bronx Analysis
# BronxSalary
BronxSalary <- Salary_edu[which(Salary_edu$Boroughs=='Bronx County'), ]
BronxSalary$year <- sub("year","",BronxSalary$year)
BronxSalary <- BronxSalary %>% select(1,3,4)

# BronxEducation
BronxEducation <- Education %>% select(1,5,6,7,20)
BronxEducation$Education_Level <- as.factor(BronxEducation$Education_Level)
BronxEducation$year <- as.factor(BronxEducation$year)
BronxEducation <- BronxEducation %>% pivot_longer(cols = !c(Education_Level,year),names_to = "Location_Gender", values_to = "count")
BronxEducation$Gender <- ifelse(BronxEducation$Location_Gender == "Bronx.County..Total", "Total", 
                             ifelse(BronxEducation$Location_Gender == "Bronx.County..Female", "Female", "Male"))
BronxEducation <- BronxEducation %>% pivot_wider(names_from = "Education_Level", values_from = "count")
BronxEducation <- BronxEducation %>% select(1,3,4,5,6,7,8)
BronxEducation<-BronxEducation[!(BronxEducation$Gender=="Total"),]

# BronxNumEmp
BronxNumEmp <- NumEmp_edu %>% select(1,2,3) %>% unique()
BronxNumEmp$Gender <- sub("Total Male","Male",BronxNumEmp$Gender)
BronxNumEmp$Gender <- sub("Total Female","Female",BronxNumEmp$Gender)
BronxNumEmp <- BronxNumEmp %>% rename("NumEmp" = "Bronx")
BronxNumEmp<-BronxNumEmp[!(BronxNumEmp$Gender=="Total"),]

# merge
Total_Bronx <- merge(BronxSalary,BronxEducation,by = c("year","Gender"))
Total_Bronx <- merge(Total_Bronx,BronxNumEmp,by = c("year","Gender"))
Total_Bronx <- Total_Bronx %>% pivot_longer(cols = c(4,5,6,7,8), names_to = "Education_Level",values_to = "NumEducated")
Total_Bronx$year <- as.factor(Total_Bronx$year)
Total_Bronx$Gender <- as.factor(Total_Bronx$Gender)
Total_Bronx$Education_Level <- as.factor(Total_Bronx$Education_Level)

# plot
ggplot(Total_Bronx,aes(NumEducated,NumEmp,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)

ggplot(Total_Bronx,aes(NumEducated,Salary_CountyGender,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)
```

```{r}
# Kings Analysis
# KingsSalary
KingsSalary <- Salary_edu[which(Salary_edu$Boroughs=='Kings County'), ]
KingsSalary$year <- sub("year","",KingsSalary$year)
KingsSalary <- KingsSalary %>% select(1,3,4)

# KingsEducation
KingsEducation <- Education %>% select(1,8,9,10,20)
KingsEducation$Education_Level <- as.factor(KingsEducation$Education_Level)
KingsEducation$year <- as.factor(KingsEducation$year)
KingsEducation <- KingsEducation %>% pivot_longer(cols = !c(Education_Level,year),names_to = "Location_Gender", values_to = "count")
KingsEducation$Gender <- ifelse(KingsEducation$Location_Gender == "Kings.County..Total", "Total", 
                             ifelse(KingsEducation$Location_Gender == "Kings.County..Female", "Female", "Male"))
KingsEducation <- KingsEducation %>% pivot_wider(names_from = "Education_Level", values_from = "count")
KingsEducation <- KingsEducation %>% select(1,3,4,5,6,7,8)
KingsEducation<-KingsEducation[!(KingsEducation$Gender=="Total"),]

# KingsNumEmp
KingsNumEmp <- NumEmp_edu %>% select(1,2,4) %>% unique()
KingsNumEmp$Gender <- sub("Total Male","Male",KingsNumEmp$Gender)
KingsNumEmp$Gender <- sub("Total Female","Female",KingsNumEmp$Gender)
KingsNumEmp <- KingsNumEmp %>% rename("NumEmp" = "Kings")
KingsNumEmp<-KingsNumEmp[!(KingsNumEmp$Gender=="Total"),]

# merge
Total_Kings <- merge(KingsSalary,KingsEducation,by = c("year","Gender"))
Total_Kings <- merge(Total_Kings,KingsNumEmp,by = c("year","Gender"))
Total_Kings <- Total_Kings %>% pivot_longer(cols = c(4,5,6,7,8), names_to = "Education_Level",values_to = "NumEducated")
Total_Kings$year <- as.factor(Total_Kings$year)
Total_Kings$Gender <- as.factor(Total_Kings$Gender)
Total_Kings$Education_Level <- as.factor(Total_Kings$Education_Level)

# plot
ggplot(Total_Kings,aes(NumEducated,NumEmp,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)

ggplot(Total_Kings,aes(NumEducated,Salary_CountyGender,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)
```

```{r}
# Queens Analysis
# QueensSalary
QueensSalary <- Salary_edu[which(Salary_edu$Boroughs=='Queens County'), ]
QueensSalary$year <- sub("year","",QueensSalary$year)
QueensSalary <- QueensSalary %>% select(1,3,4)

# QueensEducation
QueensEducation <- Education %>% select(1,14,15,16,20)
QueensEducation$Education_Level <- as.factor(QueensEducation$Education_Level)
QueensEducation$year <- as.factor(QueensEducation$year)
QueensEducation <- QueensEducation %>% pivot_longer(cols = !c(Education_Level,year),names_to = "Location_Gender", values_to = "count")
QueensEducation$Gender <- ifelse(QueensEducation$Location_Gender == "Queens.County..Total", "Total", 
                             ifelse(QueensEducation$Location_Gender == "Queens.County..Female", "Female", "Male"))
QueensEducation <- QueensEducation %>% pivot_wider(names_from = "Education_Level", values_from = "count")
QueensEducation <- QueensEducation %>% select(1,3,4,5,6,7,8)
QueensEducation<-QueensEducation[!(QueensEducation$Gender=="Total"),]

# QueensNumEmp
QueensNumEmp <- NumEmp_edu %>% select(1,2,6) %>% unique()
QueensNumEmp$Gender <- sub("Total Male","Male",QueensNumEmp$Gender)
QueensNumEmp$Gender <- sub("Total Female","Female",QueensNumEmp$Gender)
QueensNumEmp <- QueensNumEmp %>% rename("NumEmp" = "Queens")
QueensNumEmp<-QueensNumEmp[!(QueensNumEmp$Gender=="Total"),]

# merge
Total_Queens <- merge(QueensSalary,QueensEducation,by = c("year","Gender"))
Total_Queens <- merge(Total_Queens,QueensNumEmp,by = c("year","Gender"))
Total_Queens <- Total_Queens %>% pivot_longer(cols = c(4,5,6,7,8), names_to = "Education_Level",values_to = "NumEducated")
Total_Queens$year <- as.factor(Total_Queens$year)
Total_Queens$Gender <- as.factor(Total_Queens$Gender)
Total_Queens$Education_Level <- as.factor(Total_Queens$Education_Level)

# plot
ggplot(Total_Queens,aes(NumEducated,NumEmp,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)

ggplot(Total_Queens,aes(NumEducated,Salary_CountyGender,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)
```
```{r}
# Richmond Analysis
# RichmondSalary
RichmondSalary <- Salary_edu[which(Salary_edu$Boroughs=='Richmond County'), ]
RichmondSalary$year <- sub("year","",RichmondSalary$year)
RichmondSalary <- RichmondSalary %>% select(1,3,4)

# RichmondEducation
RichmondEducation <- Education %>% select(1,17,18,19,20)
RichmondEducation$Education_Level <- as.factor(RichmondEducation$Education_Level)
RichmondEducation$year <- as.factor(RichmondEducation$year)
RichmondEducation <- RichmondEducation %>% pivot_longer(cols = !c(Education_Level,year),names_to = "Location_Gender", values_to = "count")
RichmondEducation$Gender <- ifelse(RichmondEducation$Location_Gender == "Richmond.County..Total", "Total", 
                             ifelse(RichmondEducation$Location_Gender == "Richmond.County..Female", "Female", "Male"))
RichmondEducation <- RichmondEducation %>% pivot_wider(names_from = "Education_Level", values_from = "count")
RichmondEducation <- RichmondEducation %>% select(1,3,4,5,6,7,8)
RichmondEducation<-RichmondEducation[!(RichmondEducation$Gender=="Total"),]

# RichmondNumEmp
RichmondNumEmp <- NumEmp_edu %>% select(1,2,7) %>% unique()
RichmondNumEmp$Gender <- sub("Total Male","Male",RichmondNumEmp$Gender)
RichmondNumEmp$Gender <- sub("Total Female","Female",RichmondNumEmp$Gender)
RichmondNumEmp <- RichmondNumEmp %>% rename("NumEmp" = "Richmond")
RichmondNumEmp<-RichmondNumEmp[!(RichmondNumEmp$Gender=="Total"),]

# merge
Total_Richmond <- merge(RichmondSalary,RichmondEducation,by = c("year","Gender"))
Total_Richmond <- merge(Total_Richmond,RichmondNumEmp,by = c("year","Gender"))
Total_Richmond <- Total_Richmond %>% pivot_longer(cols = c(4,5,6,7,8), names_to = "Education_Level",values_to = "NumEducated")
Total_Richmond$year <- as.factor(Total_Richmond$year)
Total_Richmond$Gender <- as.factor(Total_Richmond$Gender)
Total_Richmond$Education_Level <- as.factor(Total_Richmond$Education_Level)

# plot
ggplot(Total_Richmond,aes(NumEducated,NumEmp,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)

ggplot(Total_Richmond,aes(NumEducated,Salary_CountyGender,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)
```
```{r}
# New York Analysis
# New YorkSalary
New_YorkSalary <- Salary_edu[which(Salary_edu$Boroughs=='New York County'), ]
New_YorkSalary$year <- sub("year","",New_YorkSalary$year)
New_YorkSalary <- New_YorkSalary %>% select(1,3,4)

# New_YorkEducation
New_YorkEducation <- Education %>% select(1,11,12,13,20)
New_YorkEducation$Education_Level <- as.factor(New_YorkEducation$Education_Level)
New_YorkEducation$year <- as.factor(New_YorkEducation$year)
New_YorkEducation <- New_YorkEducation %>% pivot_longer(cols = !c(Education_Level,year),names_to = "Location_Gender", values_to = "count")
New_YorkEducation$Gender <- ifelse(New_YorkEducation$Location_Gender == "New.York.County..Total", "Total", 
                             ifelse(New_YorkEducation$Location_Gender == "New.York.County..Female", "Female", "Male"))
New_YorkEducation <- New_YorkEducation %>% pivot_wider(names_from = "Education_Level", values_from = "count")
New_YorkEducation <- New_YorkEducation %>% select(1,3,4,5,6,7,8)
New_YorkEducation<-New_YorkEducation[!(New_YorkEducation$Gender=="Total"),]

# New_YorkNumEmp
New_YorkNumEmp <- NumEmp_edu %>% select(1,2,5) %>% unique()
New_YorkNumEmp$Gender <- sub("Total Male","Male",New_YorkNumEmp$Gender)
New_YorkNumEmp$Gender <- sub("Total Female","Female",New_YorkNumEmp$Gender)
New_YorkNumEmp <- New_YorkNumEmp %>% rename("NumEmp" = "New_York")
New_YorkNumEmp<-New_YorkNumEmp[!(New_YorkNumEmp$Gender=="Total"),]

# merge
Total_New_York <- merge(New_YorkSalary,New_YorkEducation,by = c("year","Gender"))
Total_New_York <- merge(Total_New_York,New_YorkNumEmp,by = c("year","Gender"))
Total_New_York <- Total_New_York %>% pivot_longer(cols = c(4,5,6,7,8), names_to = "Education_Level",values_to = "NumEducated")
Total_New_York$year <- as.factor(Total_New_York$year)
Total_New_York$Gender <- as.factor(Total_New_York$Gender)
Total_New_York$Education_Level <- as.factor(Total_New_York$Education_Level)

# plot
ggplot(Total_New_York,aes(NumEducated,NumEmp,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)

ggplot(Total_New_York,aes(NumEducated,Salary_CountyGender,color = Gender))+
  geom_point()+
  facet_wrap(~Education_Level,scales = "free_x",ncol = 2)
```

