```{r}
library(tidyverse)
Salary_NumEmp <- read.csv("/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/gdp/NYCSalary_gdp.csv")
Salary_NumEmp$X <- NULL
```

```{r}
# NumEmp
Salary_NumEmp <- Salary_NumEmp %>% select(1,2,5)

```

```{r}
Salary_NumEmp[Salary_NumEmp$Earning_category=="FULL-TIME YEAR-ROUND WORKERS WITH EARNINGS","Earning_category"] <- "Full-time year-round workers with earnings"

Salary_NumEmp[Salary_NumEmp$Earning_category=="Mean earnings (dollars) for full-time year-round workers with earnings","Earning_category"] = "Mean earnings (dollars)"

Salary_NumEmp$Earning_category <- as.factor(Salary_NumEmp$Earning_category)

Salary_NumEmp <- Salary_NumEmp %>% pivot_wider(names_from = "Earning_category", values_from = "New.York..Total")

# add GDP values
Salary_NumEmp$NYCGDP <- c(65438,65092,67565,67227,68661,69814,70781,72434,73508,75131)
Salary_NumEmp$GDP <- c(48468,49887,51611,53118,55048,56823,57928,59958,62840,65118)

Salary_NumEmp <- Salary_NumEmp %>% pivot_longer(cols = c(2:14),names_to = "Earning_Category", values_to = "Value")

```


```{r}
# plot
ggplot(Salary_NumEmp,aes(NYCGDP,Value))+
  geom_point()+
  facet_wrap(~Earning_Category,scales = "free_y")

ggplot(Salary_NumEmp,aes(GDP,Value))+
  geom_point()+
  facet_wrap(~Earning_Category,scales = "free_y")
```


