---
title: "data_preprocessing"
author: "Tracy"
date: "10/19/2020"
output: html_document
---


```{r}
library(tidyverse)
library(osmdata)
library(sf)
library(ggmap)
```

```{r}
race = read.csv(file = 'race.csv')
race$X <- NULL
colnames(race)
```

```{r}
race.long <-
  race %>% pivot_longer(cols = !c("Label", "race", "year"), names_to = "borough", values_to = "population")
```

```{r}
race.long$Label <- as.factor(race.long$Label)
race.long$race <- as.factor(race.long$race)
race.long$year <- as.factor(race.long$year)
race.long$borough <- as.factor(race.long$borough)
```


```{r,fig.width=20}
#
ggplot(data = race.long[race.long$Label=="Total:",])+
  facet_wrap(~borough)+ 
  geom_line(aes(x = year,y = population, group = race, color = race ),size = 1)
```



```{r}
#New York map
#49.23486,-123.2590805,49.2799018,-123.1966054
q <- getbb("10027") %>%
      opq() %>%
       add_osm_feature("amenity", "cinema")

str(q)

cinema <- osmdata_sf(q)
cinema
#our background map
mad_map <- get_map(getbb("10027"), maptype = "toner-background")

#final map
ggmap(mad_map)+
  geom_sf(data = cinema$osm_points,
        inherit.aes = FALSE,
        colour = "#238443",
        fill = "#004529",
        alpha = .5,
        size = 4)+
  labs(x = "", y = "")
```

